### ISSUE TITLE
ParticleGetLocationPermissionViewController does not respect replacable strings

### ISSUE THREAD

**Issue by mcgouganp** [particle-iot/particle-photon-setup-ios#12]
The strings used in ParticleGetLocationPermissionViewController, ParticleSetupStrings.GetLocationPermission.DeniedText and ParticleSetupStrings.GetLocationPermission.Text both have the word "Photon" in their default strings and the ParticleGetLocationPermissionViewController class does not respect replaceable parameters, so the token "{device}" does not work when put in a customised Strings file.

Similar to bug which was fixed in v1.0.2.

**Comment by RaimundasSakalauskas** [comment]
Thank you for reporting this. Instead of fixing a single error you reported, I tried to test it on the broader scale making sure that variables are replaced for every string before it being assigned. It's really hard to test all the prompts so there's a slight chance that something got missed, but I am sure that every string seen within views is replaced.

As a side effect - found one string that would not get replaced completely. It's the label above device name textfield in result screen.

Here's the PR For your to follow: https://github.com/particle-iot/particle-photon-setup-ios/pull/13. I would expect this to go live by the end of this week (hopefully by the end of the day tomorrow).

**Comment by mcgouganp** [comment]
Awesome. Thanks.

**Comment by RaimundasSakalauskas** [comment]
Let me know if you still have issues using v1.0.3
