### ISSUE TITLE
Library keeps user facing text in code, makes it difficult to translate

### ISSUE THREAD

**Issue by gitjoost** [particle-iot/particle-photon-setup-ios#3]
The SDK maintains user facing text in e.g. ParticleSetupResultsViewController.m. This cannot be translated without customization of the SDK and thereby (sort of) breaking future upgrades. Text should be broken out in, for example, the ParticleSetupCustomization class or a new class specifically designed for translation issues.

**Comment by gitjoost** [comment]
right ... rather then just commenting on the code I decided to do something for a change ;-)  All strings have been externalized and can now be modified - see pull request.

**Comment by RaimundasSakalauskas** [comment]
Thank you for this. And sorry both this issue and pull request has been ignored for so long. Since a lot has changed in libraries recently, the PR can no longer be merged without some serious work on it. Right now there are no immediate plans to support localization, but I will add this as a ticket so that this can be discussed within the company. Will keep an issue open and will update when something new comes up. Not sure when this can happen.

**Comment by gitjoost** [comment]
Any reason why this PR wasnt considered before the bundle of changes made recently?

**Comment by RaimundasSakalauskas** [comment]
The main reason is that we can't just localize one piece of software without localizing everything surrounding it. Right now errors being returned from server are in english, iOS SDK has all errors in english and all android libraries only support english. This is very well made PR and I wish we could just proceed with merging it, but having one product out of 5 (or even more) supporting localization might cause lots of confusion.
